"""crear_tablas_iniciales

Revision ID: 159abb3c1cc4
Revises: 
Create Date: 2026-05-02 17:50:24.981749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159abb3c1cc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_staff_firebase_uid'), 'staff', ['firebase_uid'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('internal_id', sa.String(length=50), nullable=False),
    sa.Column('public_code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('doc_tipo', sa.String(length=10), nullable=True),
    sa.Column('doc_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('allergies', sa.String(length=300), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('triage_level', sa.String(length=20), nullable=True),
    sa.Column('data_consent', sa.Boolean(), nullable=False),
    sa.Column('consent_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('companion_name', sa.String(length=200), nullable=True),
    sa.Column('companion_phone', sa.String(length=20), nullable=True),
    sa.Column('companion_relation', sa.String(length=50), nullable=True),
    sa.Column('arrived', sa.Boolean(), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_room', sa.String(length=20), nullable=True),
    sa.Column('assigned_bed', sa.String(length=20), nullable=True),
    sa.Column('attending_id', sa.String(length=36), nullable=True),
    sa.Column('attending_name', sa.String(length=200), nullable=True),
    sa.Column('share_with_companion', sa.Boolean(), nullable=False),
    sa.Column('final_diagnosis', sa.Text(), nullable=True),
    sa.Column('share_diagnosis', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attending_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_id')
    )
    op.create_index(op.f('ix_patients_public_code'), 'patients', ['public_code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('performed_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedures')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_patients_public_code'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_staff_firebase_uid'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
