"""remove_attending_fk

Revision ID: c82b7bee6bba
Revises: dbb5ba89512a
Create Date: 2026-05-03 21:23:15.803312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82b7bee6bba'
down_revision: Union[str, None] = 'dbb5ba89512a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patients_attending_id_fkey', 'patients', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('patients_attending_id_fkey', 'patients', 'staff', ['attending_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
