"""agregar_rooms_beds_doctors

Revision ID: fe2935f998fc
Revises: 11958264b270
Create Date: 2026-05-03 19:37:51.597942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2935f998fc'
down_revision: Union[str, None] = '11958264b270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'active',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('patients', 'assigned_room',
    existing_type=sa.VARCHAR(length=100),
    type_=sa.String(length=50),
    existing_nullable=True)
    op.alter_column('patients', 'assigned_bed',
    existing_type=sa.VARCHAR(length=100),
    type_=sa.String(length=50),
    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'assigned_bed',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('patients', 'assigned_room',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('doctors', 'active',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
